---
title: "September  24, 2024"
author: "CM"
date: "2024-09-24"
categories: [ "daily log", "lab notebook", "rua", "mussel biomarkers", "yellow island edna", "analysis", "planning", "presentation"]
format:
  html:
    toc: true
---

- AG meeting. I met with Alison today to review biomarker manuscript progress, update a timeline for the work that gets a polished manuscript in the hands of our WDFW collaborators and chat about navigating outside-agency collaborator relationships.\

- CG meeting. Camille and I met to realign our 2023 Yellow eDNA project goals, identify data files and any questions we had for CALeDNA and review the outputs of my dada2 work.\

After meeting with Alison I put together a shared list of tasks to complete for the manuscript draft including descriptions and deadlines. I also emailed the WDFW collaborators to remind them that we haven’t forgotten about them.
- Caroline Gibson from Salish Sea Sciences reached out and asked if I could give a presentation to 2 cohorts of area high school students about what I do and my path to grad school. I confirmed time on October 2nd for the first group and October 10th for the second.\

- Set myself up in the RUA coordinator shared office, completed WordPress training, attended the academic team meeting, cleared the email inbox and prepared for my 9.25 meeting with Julia about my progress and next steps.
