---
title: "October  4, 2024"
author: "CM"
date: "2024-10-04"
categories:
  - Lab
  - Non-Science Work
work:
  - project: "Lab Notebook"
    tasks: 
      - Brainstorming
      - Task Tracking
      - Time Management
  - project: "Personal"
    tasks: 
      - Personal
hours_spent:
  - project: "Lab Notebook"
    time: 3
  - project: "Personal"
    time: 5
format:
  html:
    toc: true
---

-   No science project progress made today as I spent the day knocking out some of my other obligations.\

-   I updated my category, project and task tags and document yaml format to better be able to reflect on where my time is spent. On my daily posts, only the categories of work tags will be present, but each daily post has a space for each project and their associated tasks that is visible to me. My efforts last month showed me that I worked in 4 major projects but didn't show me what tasks were being represented per project or how much time was spent in each. I'm trying to think about the complete processes I work though, and in an effort to survey what I'm doing to create a usable tracking system- I created some standard tags I will work from this month. My task list of tags is a bit lengthy so I won't add it here, but I believe by the end of the month I'll be able to streamline it. I'm sticking with the same ones, not making up new tasks each day, but the list is still about 25 - 30 tasks.\

**Categories** (The 'umbrella' I am working under for the day -8)\
- Degree Progress\
- Lab\
- Mentorship & Outreach\
- Non-Science Work\
- Personal Development\
- Professional Development\
- Project Progress\
- Teaching\

**Projects** (Specific project I'm working on -13 including 3 SICB 2025 projects)\
- Gray Whale Feeding\
- Learning\
- Innovation Grant\
- Innovation Grant Workshop\
- Lab Notebook\
- Mussel Biomarkers\
- Mussel Epigenetics\
- Personal Growth\
- PhD Bypass Package\
- Yellow eDNA\
- Yellow Island Program\
- Yellow Quadrats 2023\
- Yellow Quadrats 2024\
