---
title: "September  22, 2024"
author: "CM"
date: "2024-09-22"
categories: [ "daily log", "lab notebook", "project progress", "yellow island edna", "analysis"]
format:
  html:
    toc: true
---

-   Sunday
-   eDNA analysis pipeline work. I am taking some of the final steps of the dada2 pipeline to format my ASV files into usable tables and then beginning the Phyloseq work.\

Roadblock city.\

I cannot seem to manipulate the asv tables from CALeDNA into a format that is working with me. Viewing the file in a text document isn't helpful, so I converted it to a csv based on the file type and reviewed it outside of R. The columns were all the unique sample names, and the first full row was either the forward or reverse reads as indicated by the file name, followed by the sequence in the second column and counts in the table below each column - these columns were named after individual samples as well. This should have been easy enough to transform into a long-form table that had three columns: sample id, sequence and abundance. Somehow every time I transformed and attempted to label my reads as forward or reverse, the merge would remove that column and or fill it with "Null", so I attempted a long-transform of the data to then add read type back was also unsuccessful. I was wasting time trying to figure out what was going wrong with either the table transform, merge type - eventual join type...\

I just decided to go back and build the asv tables from the sequences. I followed the dada2 pipeline through asv build and saved it with considerably less headaches.
