---
title: "September  29, 2024"
author: "CM"
date: "2024-09-29"
categories: [ "daily log", "mussel biomarkers", "mentoring", "yellow island",  "project management"]
format:
  html:
    toc: true
---

-   Sunday.\

Today is day two of organization and project management.\

Before I jumped back in, I took some time in the morning to create my daily schedule for the week, add my task time blocks to my calendar and review my deliverables for the week.\

-   After that, I created the first pass of the all- Reporting Area figures for the biomarker paper. I am collapsing the sites into Reporting Ares and PAH Rankings to report each biomarker and each morphometric result. The base plots are ok, but a revisit to tweak them is time- blocked for Monday.\

-   I moved over to reviewing the Yellow Island crew's DEI application letters for the ASLOMP conference due on October 1. All 4 that submitted them to me received feedback today.\

-   After cleaning up my digital workflow yesterday, I added my ongoing projects to Clickup. I've tried several platforms (Trello, Notion, Evernote, etc.) and the problem is I don't want to reinvent the wheel, I want to maximize it. I'd like a tool that integrates my current platforms (Google drive, gmail, notes, etc.), allows for both task and project management, and can perform automated tasks based on actions within both categories. This reduces the task shuffle time suck, manual management of everything, risk of oversight and risk of over-scheduling as all projects and their tasks can be seen in a live-updated gantt chart as well one of several lists/ calendars/ whatever view you prefer.\

We'll see how this works in the free version of the platform, but for now I have transitioned all of my grad work projects over to see if it lives up to the hype. Additionally, there are time- tracking plug-ins that will help me clarify where I am spending my time each day.
