---
title: "September  23, 2024"
author: "CM"
date: "2024-09-23"
categories: [ "daily log", "lab notebook", "project progress", "rua", "yellow island edna", "analysis", "seminar"]
format:
  html:
    toc: true
---

-   Working on the phyloseq pipeline based on the asv, tronko taxonomy tables, and metadata for the 18s primer today. The asv headache returned for a victory lap as I attempted to read in the rds files needed to make the table and found that R didn't like that. I tinkered with that for far too long, so I remade the asv... I can confidently say that this part of the pipeline is crystal clear to me. I need to ask how to maintain files and the outputs of the larger projects so I don't have to rerun this process each time I want to do work - it's not feasible to run the entire pipeline and then the subsequent phyloseq pipeline based off of the file types in the first one - all in the same session.\

-   Attended a BWEEMS workshop called Next Level Tips for Winning Grants and Fellowships with ASU Professor Kiki Jenkins. We went over where to source grants and fellowships, how to prepare application pieces so that you stand out, and how to tailor your application package to align with the purpose and urgency of the funder.\

-   Reviewed RUA processes and prepared my questions for Jane and Brandon about the status of the 7 current applicants and where I can support the process and what platforms I need to learn.
