---
title: "October  22, 2024"
author: "CM"
date: "2024-10-22"
categories:
  - Project Progress 
  - Professional Development
  - Mentorship & Outreach
  - Non-science work
work:
  - project: "Growth"
    tasks: 
      - Brainstorming
      - Note taking
      - Writing
      - Webinar Attendance
  - project: "BIMS Workshop"
    tasks: 
      - Brainstorming
      - Conference preparation
      - Curriculum development
      - Planning
hours_spent:
  - project: "Growth"
    time: 2
  - project: "BIMS Workshop"
    time: 4
format:
  html:
    toc: true
---

-   Met with KPJ to discuss how to put together a teaching application. I am interested in applying for the BIOL 200 Lecturer position for the summer, so I wanted to touch base with her about how to spin my limited but varied experience into a competitive application.\

-   Angela Jones and I spent time co-working on our BIMS Workshops. We are the only workshops on the Youth & Educator night, so none of the presenter guidance thus far has been applicable to us. We spent our time sharing resources, reviewing where our programs overlap, and brainstorming how to get resources from BIMS to support our vision.\

-   I attended NOAA's information session on the 2025 Regional Ecosystem Research Program. I believe we could create a competitive proposal for this call using an integrated biomarker/ eDNA proposal. The organizers will send the session slides and pertinent recording information in the near future for revisiting.\

-   I participated in the biweekly WELLS collaboration meeting. We focused more on general community building through the organization's transition than our individual asks from the last session. We can expect to revisit the individual asks in upcoming meetings,\

-   The remainder of the day was spent on RUA tasks.
