---
title: "October  15, 2024"
author: "CM"
date: "2024-10-15"
categories:
  - Project Progress
  - Mentorship & Outreach
work:
  - project: "Mussel Biomarker"
    tasks: 
      - Seminar Preparation
  - project: "Mentorship & Outreach"
    tasks: 
      - Editing
      - Meeting Preparation
      - Meeting Attendance
hours_spent:
  - project: "Mussel Biomarker"
    time: 5
  - project: "Mentorship & Outreach"
    time: 2
format:
  html:
    toc: true
---

-   Worked on my biomarker presentation for FHL tomorrow.\

-   Edited Henry's graduate school essays.\

-   Prepared for and attended the NABS annual business meeting as the science committee representative. We will need to focus heavily on fundraising if we want to have any successful campaigns for 2025 - 2026.\

-   Prepared for and attended the WELLS community meeting. One of the focuses is on building collaborations between social sciences and 'traditional' STEAM sciences. I'm looking to collaborate with a wellness provider for next year's Yellow Island group along with building a collaborative relationship to help me with a mixed model approach to my pedagogy chapter. As I'm shaping what it could be, I am finding that it aligns greatly with both the GIS skills I'm learning and some of the geography tenets that are the frameworks for how I teach.
