---
title: October Goals
author: CM
date: October 1, 2024
categories: ["monthly goals"]
---

## Goals

Noting my struggles in September, I want to focus on appropriately blocking time for each task and creating a task list that is reflective of all of the steps needed to accomplish each goal. My goals are listed in priority for completion in the month. Flexibility exists with Goal 3 based on communication from collaborators.

### Goal 1: Biomarker manuscript draft out to WDFW collaborators by October 30th.

\[ \] Correlation plot refinement and revised Methods section. 10/9\
\[ \] Update Results and make maps to go with reporting area and PAH ranking. 10/12\
\[ \] Draft Introduction section outline, get feedback from Alison and Steven on it. 10/15\
\[ \] Continue to manage revisions, draft Introduction section and draft Discussion section 10/20\

### Goal 2: Biomarker presentation to Alison and Steven by October 13th

\[ \] Frame the story for the presentation and create slide outline. 10/8\
\[ \] Add visualizations to 'results' slides. 10/11\
\[ \] Revisit introduction slides to me & the work - what moves the story forward? Fill those slides in. 10/12\
\[ \] Add speaker notes and conclusion slides. 10/13\

### Goal 3: IG Program Packaging - Curriculum focused work.

#### This goal doesn't have a set date due to the pending collaboration and workshop pieces that haven't been confirmed as of October 6th.

\[ \] Re-familiarize myself with the existing curriculum pieces as well as where I left off building the K-12 curriculum. 10/18\
\[ \] Outline necessary milestones to complete K-12 package as well as the BIMS packet for distribution. 10/19\
\[ \] Re-familiarize myself with the EJ and Human-Connection resources and build the resource- list for future facilitators. 10/23\
\[ \] Outline workshop interactive pieces for participants to engage with the work. 10/27\
