---
title: Extractions, Concentrations, No Degredation...Oh, My!
author: CM
date: August 29, 2024
categories: [ "daily log", "project progress", "mussel epigenetics", "benchwork"]
---

## Goal

Knock out my extractions and quantify the DNA concentrations.

## Project

WDFW Mussel Epigenetics

## Purpose

There are two purposes in redoing this, first, to ensure the extraction kit didn't contribute to the failing QC score in the previous samples, and second to compare the gill and mantle tissue.

## Process

1.  Using the Omega kit protocol, I prepared all reagents and measured out the remaining volume of chloroform- isoamyl before determining how many samples could be processed. There was enough for 6 total samples, so I chose the 3 lowest DIN score samples and pulled their gill and mantle tissue packets.\
2.  The kit requires tissue samples between 30 and 50 mg. I dissected out tissue from the larger sample, recorded the dissected weight and returned the samples to the -80 freezer.\
3.  I followed the kit protocol, noting any places where the outcome differed from the intended outcome.
4.  All extracted DNA was then run through the Qubit for concentration values.\
5.  Each of the samples was put in a 10x dilution (1uL of sample + 9uL of DEIC water) before testing.\
6.  Solution and standards were prepared according to the Qubit instructions for HS DNA testing, and the samples were tested after the samples were accepted.\
7.  All samples except for one had ample DNA for assessment.\
8.  Everything was recorded and samples were placed in the -20 until gel run tomorrow.
